### ISSUE TITLE
Pretrained Cnn14 16kHz wrong shape errors

### ISSUE THREAD

**Issue by NumesSanguis** [qiuqiangkong/audioset_tagging_cnn#18]
After downloading `Cnn14_16k_mAP=0.438.pth` and following these instructions:
```bash
MODEL_TYPE="Cnn14_16k"
CHECKPOINT_PATH="Cnn14_16k_mAP=0.438.pth"   # Trained by a later version of code, achieves higher mAP than the paper.
CUDA_VISIBLE_DEVICES=0 python3 pytorch/inference.py audio_tagging --sample_rate=16000 --window_size=512 --hop_size=160 --mel_bins=64 --fmin=50 --fmax=8000 --model_type=$MODEL_TYPE --checkpoint_path=$CHECKPOINT_PATH --audio_path='resources/R9_ZSCveAHg_7s.wav' --cuda
```

I get the following error:
```python
Traceback (most recent call last):
  File "pytorch/inference.py", line 201, in <module>
    audio_tagging(args)
  File "pytorch/inference.py", line 42, in audio_tagging
    model.load_state_dict(checkpoint['model'])
  File "/home/*user*/anaconda3/envs/onseilake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Cnn14_16k:
	size mismatch for spectrogram_extractor.stft.conv_real.weight: copying a param with shape torch.Size([257, 1, 512]) from checkpoint, the shape in current model is torch.Size([129, 1, 256]).
	size mismatch for spectrogram_extractor.stft.conv_imag.weight: copying a param with shape torch.Size([257, 1, 512]) from checkpoint, the shape in current model is torch.Size([129, 1, 256]).
	size mismatch for logmel_extractor.melW: copying a param with shape torch.Size([257, 64]) from checkpoint, the shape in current model is torch.Size([129, 64]).
```

Thank you for open sourcing everything!

**Comment by qiuqiangkong** [comment]
Hi, just to confirm, have you executed: CHECKPOINT_PATH="Cnn14_16k_mAP=0.438.pth"?

**Comment by NumesSanguis** [comment]
Yes, this is the output of the variable:

```bash
echo $CHECKPOINT_PATH
# output: Cnn14_16k_mAP=0.438.pth
```

To make sure I didn't make any mistake or used outdated code (using master branch), I ran the following commands in a new terminal again:
```bash
$ git pull
Already up to date.
$ git branch
* master
$ MODEL_TYPE="Cnn14_16k"
$ CHECKPOINT_PATH="Cnn14_16k_mAP=0.438.pth"
$ echo $CHECKPOINT_PATH
Cnn14_16k_mAP=0.438.pth
$ CUDA_VISIBLE_DEVICES=0 python3 pytorch/inference.py audio_tagging --sample_rate=16000 --window_size=512 --hop_size=160 --mel_bins=64 --fmin=50 --fmax=8000 --model_type=$MODEL_TYPE --checkpoint_path=$CHECKPOINT_PATH --audio_path='resources/R9_ZSCveAHg_7s.wav' --cuda
*Same error as first post*
```

Unfortunately still the same error...

-----
Is there any chance that you renamed the wrong model (a 32k model) to `Cnn14_16k_mAP=0.438.pth` before uploading it to Zenodo?
The model I downloaded is 358.7 MB, matching the info from [version 3 of the Zenodo page](https://zenodo.org/record/3987831).

**Comment by NumesSanguis** [comment]
Here are the details of the model in case it helps:
```python
import torch
model = torch.load("Cnn14_16k_mAP=0.438.pth")
for name, tensr in model['model'].items():
    print(name, tensr.shape)
```

Output:
```python
spectrogram_extractor.stft.conv_real.weight torch.Size([257, 1, 512])
spectrogram_extractor.stft.conv_imag.weight torch.Size([257, 1, 512])
logmel_extractor.melW torch.Size([257, 64])
bn0.weight torch.Size([64])
bn0.bias torch.Size([64])
bn0.running_mean torch.Size([64])
bn0.running_var torch.Size([64])
bn0.num_batches_tracked torch.Size([])
conv_block1.conv1.weight torch.Size([64, 1, 3, 3])
conv_block1.conv2.weight torch.Size([64, 64, 3, 3])
conv_block1.bn1.weight torch.Size([64])
conv_block1.bn1.bias torch.Size([64])
conv_block1.bn1.running_mean torch.Size([64])
conv_block1.bn1.running_var torch.Size([64])
conv_block1.bn1.num_batches_tracked torch.Size([])
conv_block1.bn2.weight torch.Size([64])
conv_block1.bn2.bias torch.Size([64])
conv_block1.bn2.running_mean torch.Size([64])
conv_block1.bn2.running_var torch.Size([64])
conv_block1.bn2.num_batches_tracked torch.Size([])
conv_block2.conv1.weight torch.Size([128, 64, 3, 3])
conv_block2.conv2.weight torch.Size([128, 128, 3, 3])
conv_block2.bn1.weight torch.Size([128])
conv_block2.bn1.bias torch.Size([128])
conv_block2.bn1.running_mean torch.Size([128])
conv_block2.bn1.running_var torch.Size([128])
conv_block2.bn1.num_batches_tracked torch.Size([])
conv_block2.bn2.weight torch.Size([128])
conv_block2.bn2.bias torch.Size([128])
conv_block2.bn2.running_mean torch.Size([128])
conv_block2.bn2.running_var torch.Size([128])
conv_block2.bn2.num_batches_tracked torch.Size([])
conv_block3.conv1.weight torch.Size([256, 128, 3, 3])
conv_block3.conv2.weight torch.Size([256, 256, 3, 3])
conv_block3.bn1.weight torch.Size([256])
conv_block3.bn1.bias torch.Size([256])
conv_block3.bn1.running_mean torch.Size([256])
conv_block3.bn1.running_var torch.Size([256])
conv_block3.bn1.num_batches_tracked torch.Size([])
conv_block3.bn2.weight torch.Size([256])
conv_block3.bn2.bias torch.Size([256])
conv_block3.bn2.running_mean torch.Size([256])
conv_block3.bn2.running_var torch.Size([256])
conv_block3.bn2.num_batches_tracked torch.Size([])
conv_block4.conv1.weight torch.Size([512, 256, 3, 3])
conv_block4.conv2.weight torch.Size([512, 512, 3, 3])
conv_block4.bn1.weight torch.Size([512])
conv_block4.bn1.bias torch.Size([512])
conv_block4.bn1.running_mean torch.Size([512])
conv_block4.bn1.running_var torch.Size([512])
conv_block4.bn1.num_batches_tracked torch.Size([])
conv_block4.bn2.weight torch.Size([512])
conv_block4.bn2.bias torch.Size([512])
conv_block4.bn2.running_mean torch.Size([512])
conv_block4.bn2.running_var torch.Size([512])
conv_block4.bn2.num_batches_tracked torch.Size([])
conv_block5.conv1.weight torch.Size([1024, 512, 3, 3])
conv_block5.conv2.weight torch.Size([1024, 1024, 3, 3])
conv_block5.bn1.weight torch.Size([1024])
conv_block5.bn1.bias torch.Size([1024])
conv_block5.bn1.running_mean torch.Size([1024])
conv_block5.bn1.running_var torch.Size([1024])
conv_block5.bn1.num_batches_tracked torch.Size([])
conv_block5.bn2.weight torch.Size([1024])
conv_block5.bn2.bias torch.Size([1024])
conv_block5.bn2.running_mean torch.Size([1024])
conv_block5.bn2.running_var torch.Size([1024])
conv_block5.bn2.num_batches_tracked torch.Size([])
conv_block6.conv1.weight torch.Size([2048, 1024, 3, 3])
conv_block6.conv2.weight torch.Size([2048, 2048, 3, 3])
conv_block6.bn1.weight torch.Size([2048])
conv_block6.bn1.bias torch.Size([2048])
conv_block6.bn1.running_mean torch.Size([2048])
conv_block6.bn1.running_var torch.Size([2048])
conv_block6.bn1.num_batches_tracked torch.Size([])
conv_block6.bn2.weight torch.Size([2048])
conv_block6.bn2.bias torch.Size([2048])
conv_block6.bn2.running_mean torch.Size([2048])
conv_block6.bn2.running_var torch.Size([2048])
conv_block6.bn2.num_batches_tracked torch.Size([])
fc1.weight torch.Size([2048, 2048])
fc1.bias torch.Size([2048])
fc_audioset.weight torch.Size([527, 2048])
fc_audioset.bias torch.Size([527])
```

**Comment by qiuqiangkong** [comment]
Hi Stef,

    My bad! I have fixed this bug! The error comes from that the Cnn14_16k
model file is not updated. Just pull the latest code version, and it should
run! (Zenodo models are unchanged.) By the way, I have also added the 8 kHz
model!

    Please let me know if there are any further questions!

Best wishes,

Qiuqiang

**Comment by qiuqiangkong** [comment]
I have fixed this bug by updating pytorch/models.py. All Zenodo models are unchanged. Please git pull, and it should work!

**Comment by NumesSanguis** [comment]
It works now! Thanks for the quick fix.

There is a small issue with the instructions, however. The README.md says to use `--audio_path='resources/R9_ZSCveAHg_7s.wav'`, but that should be changed to `.mp3`.
There is no `.wav` in the folder `resources`.

**Comment by qiuqiangkong** [comment]
Hi Stef,

    I have added the wav file to resources/R9_ZSCveAHg_7s.wav. Many thanks!

Best wishes,

Qiuqiang

**Comment by NumesSanguis** [comment]
Thank you for your quick fixes! Your work will progress the field of audio deep learning!
