### ISSUE TITLE
numba.decorators ModuleNotFoundError

### ISSUE THREAD

**Issue by onnkeat** [qiuqiangkong/audioset_tagging_cnn#46]
Hi. I got this error when trying to run `pytorch/inference.py` . 
I installed the required packages by running `pip install -r requirements.txt`

Below is the traceback:

`Traceback (most recent call last):
  File "pytorch/inference.py", line 6, in <module>
    import librosa
  File "/usr/local/lib/python3.7/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/__init__.py", line 109, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.7/dist-packages/librosa/util/__init__.py", line 71, in <module>
    from . import decorators
  File "/usr/local/lib/python3.7/dist-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'`

**Comment by aishwaryajadhav** [comment]
I faced the same issue. Install the latest version of librosa. Not the one mentioned in requirements.txt

**Comment by hshjerry** [comment]
Me too

**Comment by ilileun** [comment]
me too
